### ISSUE TITLE
Yarn Directions

### ISSUE THREAD

**Issue by mscheppmann** [devowlio/wp-react-starter#21]
Hey there!  Per your installation instructions, your step for Yarn states:
`$ yarn add -g create-wp-react-app`

This syntax would be correct for NPM, but one caveat of using yarn is that the syntax to globally download packages is actually:
`$ yarn global add create-wp-react-app`

Just wanted to let you know that I was unable to install the package globally until using the latter code, thanks!

**Comment by matzeeable** [comment]
Hi @mscheppmann !

Thanks for your issue. We have worked hard on this project since a few month and released finally a complete rewrite of the boilerplate. If you want to checkout: https://devowlio.gitbook.io/wp-react-starter/ 🙂
