### ISSUE TITLE
some test fails when create plugin from create-wp-react-app

### ISSUE THREAD

**Issue by geopamplona** [devowlio/wp-react-starter#23]
Hi, 

Since yesterday I am not able to compile correctly.

![imagen](https://user-images.githubusercontent.com/25028240/76343912-0cdabb80-6301-11ea-8935-5f0bad93d7b1.png)

some tests fails
I am using last version from `create-wp-react-app`

Thanks !

**Comment by matzeeable** [comment]
Hi!

What's the exact version you are using? What command have you executed?

**Comment by geopamplona** [comment]
i execute `create-wp-react-app create-workspace` with version 2.1.0

**Comment by matzeeable** [comment]
Fixed by https://github.com/devowlio/create-wp-react-app/commit/391779a55f2769bc5c548d649b1d5dea73738714 . Please update to `create-wp-react-app@2.1.1` and let me know if it works. If it does not, reopen the issue. 😃
