### ISSUE TITLE
Example of extending the webpack config

### ISSUE THREAD

**Issue by fedorenkodev** [devowlio/wp-react-starter#24]
Hey guys,
Could anybody please provide an example of extending the webpack config? Especially how to add the new plugin. 
Thanks.

**Comment by matzeeable** [comment]
Hi @fedorenkodev !

Thanks for your question! Did you checkout the API here: https://devowlio.gitbook.io/wp-react-starter/advanced/extend-compose-webpack#webpack ?

If you want to add another plugin, you can do something like this:

```typescript
import { createDefaultSettings } from "../../../common/webpack.factory";
import { BundleAnalyzerPlugin } from "webpack-bundle-analyzer";

export default createDefaultSettings("plugin", {
    override: ([config]) => {
		config.plugins.push(
			new BundleAnalyzerPlugin()
		);
    }
});
```

Regards,
Matthew 😎

**Comment by fedorenkodev** [comment]
Looks good to me, just wanted to clarify if its the correct way to use the push method.
Thanks!
