### ISSUE TITLE
How to use static assets inside SASS styles?

### ISSUE THREAD

**Issue by fedorenkodev** [devowlio/wp-react-starter#28]
Hey guys, how I can use e.g. png image inside an scss file of a plugin? How should I store the image inside the plugin folder and what path to use to get it?

Thanks!

**Comment by matzeeable** [comment]
Hi @fedorenkodev !

Thanks for your message. You should think about the following points:

- Put your assets into e. g. `src/public/assets/images`
- Refer from your SCSS relatively, e. g. `background-image: url('../assets/images/')`

Regards,
Matthew :-)

**Comment by fedorenkodev** [comment]
@matzeeable it works for me, many thanks
